name = "Clean"
license = "MIT"
licenselink = "https://github.com/xiaoxinghu/clean/blob/master/LICENSE.md"
description = "Hugo theme with webpack and react."
homepage = "https://github.com/xiaoxinghu/clean/"
tags = ["blog", "plain", "blank", "starter"]
features = ["blog"]
min_version = 0.19

[author]
  name = "Xiaoxing Hu"
  homepage = "http://huxiaoxing.com/"